### ISSUE TITLE
Provide an example Cobalt Strike dataset for contributors

### ISSUE THREAD

**Issue by beescuit** [cisagov/RedEye#12]
I'm interested in contributing to the project by helping implement new parsers for known C2 frameworks.
As Cobalt Strike is behind a paywall, it would be awesome if a sample log folder/dataset was provided so people that don't have access to CS could test and contribute to RedEye.

**Comment by GoldingAustin** [comment]
Thanks for creating a ticket and your interest in contributing! We have a small sample dataset (which we use for end-to-end testing) you can upload in the repo here: https://github.com/cisagov/RedEye/blob/develop/applications/redeye-e2e/src/fixtures/gt.redeye We will be adding another dataset in the next couple weeks

We'll also be working on a guide for creating new parsers: https://github.com/cisagov/RedEye/issues/11#issuecomment-1281568520
