### ISSUE TITLE
Updates to parsed campaigns

### ISSUE THREAD

**Issue by lengers** [cisagov/RedEye#15]
**Is your feature request related to a problem? Please describe.**
We are planning on using RedEye as a visualization tool during our red team assessments. As of now, it seems like RedEye is unable to add data to a campaign once it has been parsed initially.

**Describe the solution you'd like**
A solution to allow upload of additional/updated log files would allow RedEye to be used as a live-view of a running campaign. 

**Describe alternatives you've considered**
I attempted to create a wrapper script that parses new log files and uploads them to the API with the corresponding campaign ID, but it seems like this is currently not supported. As of now, I don't see an alternative way. 

**Additional context**
None

**Comment by devanfarrell** [comment]
Thank you for the issue! We currently have a concept for live parsing in progress. When we release it, note that it is still very much a work in progress but we're pretty excited about it.

**Comment by GoldingAustin** [comment]
Thanks for the feedback! I'm closing this issue to centralize discussion on live parsing to #32
