### ISSUE TITLE
Blue Team or Red Team Mode Indication

### ISSUE THREAD

**Issue by MarkisK** [cisagov/RedEye#17]
**Is your feature request related to a problem? Please describe.**
When using the application there is really no way to distinguish if a user is in blue team(review) mode or red team

**Describe the solution you'd like**
There should be an indication somewhere within the main view or once a user logs in letting them know what mode they are in

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Yablargo** [comment]
Looking at the UI, it is pretty clean and I'm a little torn on where the notification would go. It would be pretty non-destructive to put it in the tab/page title but that might not be obvious to a lot of users.

**Comment by GoldingAustin** [comment]
Fixed in #75
