### ISSUE TITLE
User setting displaying incorrect data

### ISSUE THREAD

**Issue by MarkisK** [cisagov/RedEye#18]
**Describe the bug**
The user setting is displaying incorrect data

**To Reproduce**
1. Log into the application
2. Click the user setting button at the top of the screen
3. The Change user.name did not render correctly as shown

**Expected behavior**
Should show as change name or the actual name of the user

**Screenshots**
![Screen Shot 2022-10-18 at 4 44 31 PM](https://user-images.githubusercontent.com/20728284/196543949-113897ce-34cc-41c5-a5e3-506f8def8cda.png)

**Desktop (please complete the following information):**
- OS: [Mac]
- Browser [Firefox]
- Version [105]

**Additional context**

**Comment by GoldingAustin** [comment]
This is displaying as intended but we need to do a review of the wording and/or function of this dialog! Thanks for submitting this with a great description and screenshot :)

**Comment by MarkisK** [comment]
@GoldingAustin being that it's reactive and the way it looks as if it didn't render whatever data was intended. I can look into it more but the dot notation(user.name) is somewhat of an indicator of that. I would love to fix some of these issues but I see it isn't open just yet. Keep up the great work
