### ISSUE TITLE
Stuck when importing C/S logs 

### ISSUE THREAD

**Issue by mxlgg** [cisagov/RedEye#19]
After selecting C/S logs for import, the page stays at Importing... Status
![image](https://user-images.githubusercontent.com/82816532/196627587-9703385d-47f8-492f-a7f4-bbeb70ac98b9.png)
The error message reported on the server is as follows
PARSING ERROR: error in exec callback {
  error: Error: spawn /home/test/linux/test/parsers/cs-parser ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
      at onErrorNT (node:internal/child_process:478:16)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawn /home/test/linux/test/parsers/cs-parser',
    path: '/home/test/linux/test/parsers/cs-parser',
    spawnargs: [
      'campaign',
      '-d',
      '/home/test/linux/test/campaign/13aafb0c-ecb4-43c8-827a-542c7a3c5ac6/db.redeye',
      '-p',
      '/home/test/linux/test/campaign/13aafb0c-ecb4-43c8-827a-542c7a3c5ac6',
      '-t',
      '7'
    ],
    cmd: '/home/test/linux/test/parsers/cs-parser campaign -d /home/test/linux/test/campaign/13aafb0c-ecb4-43c8-827a-542c7a3c5ac6/db.redeye -p /home/test/linux/test/campaign/13aafb0c-ecb4-43c8-827a-542c7a3c5ac6 -t 7'
  },
  stdout: '',
  stderror: ''
}
![image](https://user-images.githubusercontent.com/82816532/196627766-53b9a91b-c18f-444e-b312-4ac5c41e3fcb.png)

**Comment by mxlgg** [comment]
I have solved this problem, which was due to the implementation of . /RedEye without using Root permissions

**Comment by sang2925** [comment]
@mxlgg thank you for the follow up post. Please let us know if you run into any other issues!
