### ISSUE TITLE
Missing ability to create new campaign

### ISSUE THREAD

**Issue by jharbin** [cisagov/RedEye#22]
**Describe the bug**
Trying to create a new initial campaign, but only have the ability to import a campaign and DB files.

**To Reproduce**
1. Login
2. Click on 'Add a Campaign +'
3. See error

**Expected behavior**
Screen shots on User Guide show "Create Campaign" but not in my run. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20796305/196987344-f0b34b7c-11cf-4a0c-b5f1-26091c9c5af3.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser Firefox
- Version 102.3.0esr (64-bit)

**Additional context**
Running Windows:  RedEye Server v0.8.0-beta w/no additional parameters in originally "empty" directory.  

**Am I missing a config to allow new campaigns?  Is there a sample or an empty campaign that I can import for now to "create"?**

**Comment by sang2925** [comment]
@jharbin 
It appears you are running the blue team version, which only has the ability to upload and import DB files. Could you run the red team version of RedEye and see if the same behavior happens for you?

**Comment by jharbin** [comment]
Ahh... set environment variable and kicked it off in RedTeam mode.. now I get the Server Auth and then I can create a campaign... question though..  is it not possible to create an empty campaign that I can manually add data to for tracking?  I don't have CS data to seed the campaign with and it seems like I have to even with the "Create New" option.

![image](https://user-images.githubusercontent.com/20796305/197001566-43659366-c957-4dac-b239-9f77058f24c0.png)
