### ISSUE TITLE
Add Information about setting up E2E Testing in README.md or Contribution Area

### ISSUE THREAD

**Issue by MarkisK** [cisagov/RedEye#23]
**Is your feature request related to a problem? Please describe.**
Its not very clear how to set up the end to end testing which is a part of this project to contribute to it.

**Describe the solution you'd like**
Add a section in the read me file about how to set up the end to end testing and getting a projectId for contribution

**Describe alternatives you've considered**

**Additional context**
Not sure how to deal with these as check in because I assume the id is unique and it gets added to the cypress.config file. There should probably be an environment variable that can be set some where for the global project unless the intention is for each user to check in one but that would mean it would be checked in with the changes from the previous authors check in and projectId for testing

**Comment by GoldingAustin** [comment]
Local testing is setup automatically on install, the `projectId` is not required. I will add a section in the `CONTRIBUTING.MD` that includes `yarn run test` to run the tests. Thanks for the issue!
