### ISSUE TITLE
[Feature Request] Criminal IP

### ISSUE THREAD

**Issue by pypygeek** [cisagov/RedEye#25]
Hello,
thank you for the good service.

Can you add [Criminal IP](https://www.criminalip.io)?

if it matches for IP and URL, I would like to move to Criminal IP search result.
like Mitre TID

![command](https://user-images.githubusercontent.com/19469996/197456058-891fe348-6c91-4644-8b85-b3aca1b6fee2.png)

**Comment by randaal** [comment]
this doesn't make a lot of sense for any real use case for a red team use case --- could you explain more please? this isnt meant for investing malicious IP addresses, or marking anything malicious, RedEye is meant to show an attack path visuall.
