### ISSUE TITLE
Clicking in the "bar graph area" of the timeline should move the time slider.

### ISSUE THREAD

**Issue by Yablargo** [cisagov/RedEye#31]
**Is your feature request related to a problem? Please describe.**

When I first used RedEye, I attempted to navigate the time slider by clicking into the upper 'canvas' area with the activity bar graph as (poorly) circled here.
![image](https://user-images.githubusercontent.com/4755200/200049168-976c9f70-4e6a-489a-88a3-3814184d71ca.png)

Since this UI doesn't do anything else, it might be a nice improvement to jump the timeline to the area clicked.

Tt might just be, but that was the first thing I tried to do when I inspected the timeline, and it did not work as expected.

**Describe the solution you'd like**
Clicking in the area above the draggable dot jumps the dot to the horizontal spot you clicked on.

**Describe alternatives you've considered**
I guess the current implementation is the most obvious alternative.

**Comment by sang2925** [comment]
@Yablargo 
You can drag the slider/scrubber left and right to your desired timeline position.

**Comment by GoldingAustin** [comment]
To add, we have plans to make the bar graph area more interactive with hover and click states that show a summary of hosts/beacons/commands within a timestep. I understand the gap in functionality currently, and if we weren't planning on expanding this feature, we would implement your suggestion! Thanks so much for the feedback and feature request!

**Comment by Yablargo** [comment]
Ok, in that case I will close this. I mostly submitted it because it was otherwise "dead" UI space.
