### ISSUE TITLE
"How-to" guide for writing a RedEye parser

### ISSUE THREAD

**Issue by GoldingAustin** [cisagov/RedEye#34]

**Comment by jus0xA** [comment]
Is this still on the drawing board for this year?

**Comment by GoldingAustin** [comment]
> Is this still on the drawing board for this year? I feel this may be a good example of "teaching how to fish" vs "giving someone a fish", allowing the community as a whole to help contribute parsers vs your team having to make them for each individual framework.

Yes this is! We'll be releasing the how-to guide after the [custom parser foundation PR](https://github.com/cisagov/RedEye/pull/143) is merged. We've reworked RedEye's parsing system to make it as simple as possible to create a custom parser and integrate it into RedEye
