### ISSUE TITLE
Export fails on campaign with hidden hosts

### ISSUE THREAD

**Issue by simplysean** [cisagov/RedEye#39]
**Describe the bug**
Export of campaign fails if campaign contains hidden hosts.

**To Reproduce**
1. Create a campaign by importing logs
2. Hide a host
3. Export the campaign with option 'Remove all hidden Beacons, Hosts, and Servers' checked

**Expected behavior**
Campaign to successfully export and the exported campaign does not contain the host(s) that were hidden.

**Screenshots**
<img width="719" alt="Screen Shot 2022-11-10 at 11 29 41 PM" src="https://user-images.githubusercontent.com/112509352/201263925-772e61c0-305d-47eb-939c-c80ec68e07c1.png">
<img width="869" alt="Screen Shot 2022-11-10 at 11 30 42 PM" src="https://user-images.githubusercontent.com/112509352/201263941-6650d369-2f17-4edc-b357-a856a67fa82d.png">

**Desktop (please complete the following information):**
- OS: macOS Monterey
- Browser: Chrome
- Version: 107.0.5304.110 

**Additional context**
I created a campaign, and then hid two hosts (SA-WIN10-21H1-1 and SA-DC01-2019).  I then attempted to export the campaign with the option 'Remove all hidden Beacons, Hosts, and Servers' checked, and received the errors in the above screenshots.

**Comment by GoldingAustin** [comment]
Thanks for creating a ticket for this! This has been fixed and will be included in the next release tomorrow! It will only work on future campaign uploads; we are working on a simple way to migrate eligible campaigns on version updates and when database schema changes are made.
