### ISSUE TITLE
Forensic Version

### ISSUE THREAD

**Issue by LIONBDX33** [cisagov/RedEye#63]
Would a forensic version be possible? It would allow the use of redEye for the analysis of cobaltstrike cybercriminal C2 servers. 

Unlike a RedTeam, Cobaltstrike is used on simultaneous multi-campaigns.
![image](https://user-images.githubusercontent.com/116147289/212885337-dddb44d9-0a70-440d-99d0-839f82fea361.png)

This requires much more resources for the graphical display

On this version, it could have for example :

- The IP of the attacker enriched with the country
- The public IP of the victim enriched with the country
- Possibility to display only one "victim and export the result in a new campaign
- Possibility to display only one attacker and export the result in a new campaign

Thanks

**Comment by randaal** [comment]
this is not the intended use case for RedEye.
