### ISSUE TITLE
Our security product uses the name RedEye

### ISSUE THREAD

**Issue by adamziaja** [cisagov/RedEye#8]
Our threat hunting product has been using the **RedEye name for the past 3 years**.
- https://rtfs.pl/pl/threat-hunting.html / https://rtfs.pl/en/threat-hunting.html
- https://redteam.pl/pl/threat-hunting-intelligence.html / https://redteam.pl/en/threat-hunting-intelligence.html
- https://redteam.pl/pl/soc-security-operations-center.html / https://redteam.pl/en/soc-security-operations-center.html
- https://forsec.pl/wp-content/uploads/2021/08/SOC_opis.pdf - there's even a logo depicting a _red eye_ on the 10th page
- https://redteam.pl/images/04.svg - logo of our product RedEye
etc

Is it possible for you to change the name to avoid confusion? Our product is commercial and also intended for an identical purpose.

Our RED TEAM company is also well-known in the foreign market, including the United States:
- https://www.forbes.com/sites/leemathews/2020/08/25/apple-safari-bug-steal-files/
- https://isc.sans.edu/podcastdetail.html?id=7138
- https://isc.sans.edu/podcastdetail.html?id=6484
- https://www.zdnet.com/article/security-researcher-discloses-safari-bug-after-apples-delays-patch/
- https://www.bleepingcomputer.com/news/security/black-kingdom-ransomware-hacks-networks-with-pulse-vpn-flaws/
- https://clutch.co/profile/redteampl#reviews
etc

**Comment by daddycocoaman** [comment]
Ay, this funny AF.

**Comment by ackroute** [comment]
> intended for an identical purpose.  

This is a red team report visualization tool, while your product appears to be an IPS with extra steps that's operated by a SOC-as-a-Service. What is the identical purpose?

Also, this company - https://www.redeye.tech/ - has been using the RedEye name for the **past 17 years**, so if anyone has a right to complain here it's probably them.

**Comment by fsacer** [comment]
It also has the same name as https://github.com/redeye-framework/Redeye which is a data-management tool for pentesting.
