### ISSUE TITLE
Exits without errors but nothing happens

### ISSUE THREAD

**Issue by SkyperTHC** [cisagov/RedEye#98]
(disclaimer: I'm trying to help a user. I'm not the user and not using redeye but just the messenger reporting this bug).

using the static binary from your release page on a remote server.  I can start RedEye but it exists after 1 second without any output:

```shell
ssh -L5900:0:5900 root@teso.segfaul.net # password is 'segfault'
startxvnc
```

Connect to 127.0.0.1:5900 with any VNC client, then start RedEye in an Xterm:

```shell
┌──(root💀sf-TellPistol)-[~]
└─# ./RedEye

┌──(root💀sf-TellPistol)-[~]
└─#
```

No output. No process is started.

**Comment by GoldingAustin** [comment]
@SkyperTHC Could you please have the user try to rerun RedEye with the latest release? We've made some updates that might have fixed this problem, or it will display details on what is causing RedEye to exit without running.

**Comment by SkyperTHC** [comment]
Yep. That's now working fine. THANK YOU. ❤️
